In [2]:
# importações
from utils import *
from utils_backtest import *
from models import *
from config import *

# 1. Aplicabilidade do Modelo 2 no Mercado Real

In [3]:
# Lista de ações
stock_list = ['PETR4', 'VALE3', 'BBDC4','ITUB4']

# Carrega os dados de todas as ações e calcula os indicadores e salva em um dicionario
all_stock_data = load_stocks_data(stock_list)

Carregando dados para: PETR4
Carregando dados para: VALE3
Carregando dados para: BBDC4
Carregando dados para: ITUB4

## 2. Processar o Treino do Modelo para Salvar os artefatos

In [4]:
# Processando o Modelo 2 para Salvar os Artefatos (modelo e scalers)

name_model = model_2 # Modelo 2
num_combination = 4 # Combinação 4

'''
7 combinações de dados disponíveis: 
     1. Stock Data
     2. Stock Data + Google News
     3. Stock Data + Twitter 
     4. Stock Data + (IFR + MMS + MME) 
     5. Google News + Twitter + IFR + MMS 
     6. Google News + Twitter + IFR + MME
     7. Google News + Twitter + IFR + MME + MMS 
'''

result = process_stocks_and_save_metrics(all_stock_data, num_combination, name_model, save_artifacts=True) # Salva os artefatos

model_2: Processando PETR4 | Combinação 4...
Epoch 1/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 6s 30ms/step - loss: 0.0542 - mae: 0.1647 - mape: 2788.4358 - mse: 0.0542 - val_loss: 6.2186e-04 - val_mae: 0.0177 - val_mape: 4.3566 - val_mse: 6.2186e-04
Epoch 2/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 4.7139e-04 - mae: 0.0165 - mape: 1005.2806 - mse: 4.7139e-04 - val_loss: 4.9592e-04 - val_mae: 0.0168 - val_mape: 3.9543 - val_mse: 4.9592e-04
Epoch 3/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 2.7392e-04 - mae: 0.0119 - mape: 313.1542 - mse: 2.7392e-04 - val_loss: 3.8427e-04 - val_mae: 0.0137 - val_mape: 3.2776 - val_mse: 3.8427e-04
Epoch 4/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 2.6155e-04 - mae: 0.0118 - mape: 281.9212 - mse: 2.6155e-04 - val_loss: 3.9777e-04 - val_mae: 0.0142 - val_mape: 3.3612 - val_mse: 3.9777e-04
Epoch 5/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - loss: 2.5576e-04 - mae: 0.0114 - mape: 205.2205 - mse: 2.5576e-04 - val_loss: 6.2636e-04 - val_mae: 0.0205 - val_mape: 4.6455 - val_mse: 6.2636e-04
Epoch 6/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 2.5428e-04 - mae: 0.0114 - mape: 347.0480 - mse: 2.5428e-04 - val_loss: 7.1281e-04 - val_mae: 0.0225 - val_mape: 5.0402 - val_mse: 7.1281e-04
Epoch 7/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 2.6904e-04 - mae: 0.0116 - mape: 303.1002 - mse: 2.6904e-04 - val_loss: 6.0608e-04 - val_mae: 0.0202 - val_mape: 4.5572 - val_mse: 6.0608e-04
Epoch 8/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 2.6800e-04 - mae: 0.0119 - mape: 356.5684 - mse: 2.6800e-04 - val_loss: 4.2562e-04 - val_mae: 0.0154 - val_mape: 3.5859 - val_mse: 4.2562e-04
Epoch 9/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 2.3793e-04 - mae: 0.0112 - mape: 469.8113 - mse: 2.3793e-04 - val_loss: 4.1512e-04 - val_mae: 0.0152 - val_mape: 3.5142 - val_mse: 4.1512e-04
Epoch 10/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 2.5739e-04 - mae: 0.0119 - mape: 363.3505 - mse: 2.5739e-04 - val_loss: 4.0224e-04 - val_mae: 0.0148 - val_mape: 3.4338 - val_mse: 4.0224e-04
Epoch 11/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 2.3984e-04 - mae: 0.0115 - mape: 375.5176 - mse: 2.3984e-04 - val_loss: 4.5505e-04 - val_mae: 0.0165 - val_mape: 3.7529 - val_mse: 4.5505e-04
Epoch 12/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 2.4457e-04 - mae: 0.0114 - mape: 471.5308 - mse: 2.4457e-04 - val_loss: 3.6061e-04 - val_mae: 0.0135 - val_mape: 3.1585 - val_mse: 3.6061e-04
Epoch 13/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 2.6092e-04 - mae: 0.0118 - mape: 415.5539 - mse: 2.6092e-04 - val_loss: 3.3386e-04 - val_mae: 0.0125 - val_mape: 2.9603 - val_mse: 3.3386e-04
Epoch 14/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 2.4856e-04 - mae: 0.0115 - mape: 429.2888 - mse: 2.4856e-04 - val_loss: 3.1854e-04 - val_mae: 0.0117 - val_mape: 2.8083 - val_mse: 3.1854e-04
Epoch 15/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 2.2544e-04 - mae: 0.0108 - mape: 491.1368 - mse: 2.2544e-04 - val_loss: 3.7516e-04 - val_mae: 0.0131 - val_mape: 3.1066 - val_mse: 3.7516e-04
Epoch 16/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 2.3202e-04 - mae: 0.0111 - mape: 587.8667 - mse: 2.3202e-04 - val_loss: 3.6924e-04 - val_mae: 0.0140 - val_mape: 3.2429 - val_mse: 3.6924e-04
Epoch 17/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 2.4719e-04 - mae: 0.0114 - mape: 460.4070 - mse: 2.4719e-04 - val_loss: 3.2177e-04 - val_mae: 0.0122 - val_mape: 2.8781 - val_mse: 3.2177e-04
Epoch 18/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 2.2060e-04 - mae: 0.0108 - mape: 498.5554 - mse: 2.2060e-04 - val_loss: 3.1235e-04 - val_mae: 0.0116 - val_mape: 2.7642 - val_mse: 3.1235e-04
Epoch 19/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 2.3901e-04 - mae: 0.0111 - mape: 600.5615 - mse: 2.3901e-04 - val_loss: 4.6851e-04 - val_mae: 0.0171 - val_mape: 3.8978 - val_mse: 4.6851e-04
Epoch 20/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.5660e-04 - mae: 0.0116 - mape: 721.4383 - mse: 2.5660e-04 - val_loss: 3.1117e-04 - val_mae: 0.0116 - val_mape: 2.7712 - val_mse: 3.1117e-04
Epoch 21/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.3040e-04 - mae: 0.0109 - mape: 726.3498 - mse: 2.3040e-04 - val_loss: 4.0002e-04 - val_mae: 0.0151 - val_mape: 3.4849 - val_mse: 4.0002e-04
Epoch 22/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.6473e-04 - mae: 0.0119 - mape: 768.8973 - mse: 2.6473e-04 - val_loss: 3.3502e-04 - val_mae: 0.0129 - val_mape: 3.0209 - val_mse: 3.3502e-04
Epoch 23/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.4048e-04 - mae: 0.0112 - mape: 767.8541 - mse: 2.4048e-04 - val_loss: 4.4203e-04 - val_mae: 0.0164 - val_mape: 3.7519 - val_mse: 4.4203e-04
Epoch 24/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.3203e-04 - mae: 0.0111 - mape: 666.3118 - mse: 2.3203e-04 - val_loss: 3.0928e-04 - val_mae: 0.0116 - val_mape: 2.7561 - val_mse: 3.0928e-04
Epoch 25/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.2242e-04 - mae: 0.0108 - mape: 794.3576 - mse: 2.2242e-04 - val_loss: 3.4514e-04 - val_mae: 0.0133 - val_mape: 3.0938 - val_mse: 3.4514e-04
Epoch 26/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.2249e-04 - mae: 0.0109 - mape: 694.5642 - mse: 2.2249e-04 - val_loss: 3.0556e-04 - val_mae: 0.0115 - val_mape: 2.7329 - val_mse: 3.0556e-04
Epoch 27/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.0138e-04 - mae: 0.0101 - mape: 889.8646 - mse: 2.0138e-04 - val_loss: 3.3501e-04 - val_mae: 0.0129 - val_mape: 3.0184 - val_mse: 3.3501e-04
Epoch 28/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.1470e-04 - mae: 0.0106 - mape: 943.7545 - mse: 2.1470e-04 - val_loss: 3.6040e-04 - val_mae: 0.0138 - val_mape: 3.2215 - val_mse: 3.6040e-04
Epoch 29/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.2169e-04 - mae: 0.0107 - mape: 686.1194 - mse: 2.2169e-04 - val_loss: 3.1665e-04 - val_mae: 0.0122 - val_mape: 2.8790 - val_mse: 3.1665e-04
Epoch 30/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.2415e-04 - mae: 0.0108 - mape: 773.9835 - mse: 2.2415e-04 - val_loss: 2.9949e-04 - val_mae: 0.0114 - val_mape: 2.7054 - val_mse: 2.9949e-04
Epoch 31/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.2490e-04 - mae: 0.0108 - mape: 868.7493 - mse: 2.2490e-04 - val_loss: 3.0486e-04 - val_mae: 0.0117 - val_mape: 2.7688 - val_mse: 3.0486e-04
Epoch 32/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.2104e-04 - mae: 0.0106 - mape: 894.0792 - mse: 2.2104e-04 - val_loss: 3.2856e-04 - val_mae: 0.0128 - val_mape: 2.9807 - val_mse: 3.2856e-04
Epoch 33/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.4200e-04 - mae: 0.0113 - mape: 743.4789 - mse: 2.4200e-04 - val_loss: 3.2587e-04 - val_mae: 0.0120 - val_mape: 2.8534 - val_mse: 3.2587e-04
Epoch 34/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.1073e-04 - mae: 0.0104 - mape: 903.4436 - mse: 2.1073e-04 - val_loss: 3.5320e-04 - val_mae: 0.0137 - val_mape: 3.1658 - val_mse: 3.5320e-04
Epoch 35/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.1993e-04 - mae: 0.0108 - mape: 812.5615 - mse: 2.1993e-04 - val_loss: 2.9767e-04 - val_mae: 0.0114 - val_mape: 2.6965 - val_mse: 2.9767e-04
Epoch 36/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.0904e-04 - mae: 0.0103 - mape: 631.1432 - mse: 2.0904e-04 - val_loss: 3.7578e-04 - val_mae: 0.0145 - val_mape: 3.2988 - val_mse: 3.7578e-04
Epoch 37/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.3055e-04 - mae: 0.0111 - mape: 939.3320 - mse: 2.3055e-04 - val_loss: 3.0402e-04 - val_mae: 0.0114 - val_mape: 2.7366 - val_mse: 3.0402e-04
Epoch 38/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.1237e-04 - mae: 0.0105 - mape: 1010.6085 - mse: 2.1237e-04 - val_loss: 5.8977e-04 - val_mae: 0.0202 - val_mape: 4.4807 - val_mse: 5.8977e-04
Epoch 39/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.6271e-04 - mae: 0.0119 - mape: 911.7853 - mse: 2.6271e-04 - val_loss: 3.2022e-04 - val_mae: 0.0125 - val_mape: 2.9142 - val_mse: 3.2022e-04
Epoch 40/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.1771e-04 - mae: 0.0106 - mape: 925.3513 - mse: 2.1771e-04 - val_loss: 2.9735e-04 - val_mae: 0.0116 - val_mape: 2.7254 - val_mse: 2.9735e-04
Epoch 41/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.2499e-04 - mae: 0.0108 - mape: 834.9175 - mse: 2.2499e-04 - val_loss: 3.0083e-04 - val_mae: 0.0115 - val_mape: 2.7348 - val_mse: 3.0083e-04
Epoch 42/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.0735e-04 - mae: 0.0105 - mape: 945.0275 - mse: 2.0735e-04 - val_loss: 3.0040e-04 - val_mae: 0.0117 - val_mape: 2.7590 - val_mse: 3.0040e-04
Epoch 43/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.1243e-04 - mae: 0.0105 - mape: 783.6344 - mse: 2.1243e-04 - val_loss: 3.9603e-04 - val_mae: 0.0152 - val_mape: 3.4370 - val_mse: 3.9603e-04
Epoch 44/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.2100e-04 - mae: 0.0108 - mape: 900.9708 - mse: 2.2100e-04 - val_loss: 3.4791e-04 - val_mae: 0.0136 - val_mape: 3.1166 - val_mse: 3.4791e-04
Epoch 45/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.3415e-04 - mae: 0.0111 - mape: 922.1945 - mse: 2.3415e-04 - val_loss: 3.0070e-04 - val_mae: 0.0118 - val_mape: 2.7689 - val_mse: 3.0070e-04
Epoch 46/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.1985e-04 - mae: 0.0107 - mape: 808.8231 - mse: 2.1985e-04 - val_loss: 2.9136e-04 - val_mae: 0.0113 - val_mape: 2.6888 - val_mse: 2.9136e-04
Epoch 47/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.0081e-04 - mae: 0.0101 - mape: 963.6061 - mse: 2.0081e-04 - val_loss: 2.9005e-04 - val_mae: 0.0113 - val_mape: 2.6883 - val_mse: 2.9005e-04
Epoch 48/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.1298e-04 - mae: 0.0105 - mape: 706.6560 - mse: 2.1298e-04 - val_loss: 3.8725e-04 - val_mae: 0.0149 - val_mape: 3.3756 - val_mse: 3.8725e-04
Epoch 49/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.2945e-04 - mae: 0.0110 - mape: 661.0701 - mse: 2.2945e-04 - val_loss: 3.1485e-04 - val_mae: 0.0118 - val_mape: 2.8427 - val_mse: 3.1485e-04
Epoch 50/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.1343e-04 - mae: 0.0106 - mape: 495.4490 - mse: 2.1343e-04 - val_loss: 3.0760e-04 - val_mae: 0.0116 - val_mape: 2.7959 - val_mse: 3.0760e-04

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
model_2: Processando VALE3 | Combinação 4...
Epoch 1/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 0.0795 - mae: 0.2012 - mape: 95627.7812 - mse: 0.0795 - val_loss: 0.0212 - val_mae: 0.1125 - val_mape: 9.3827 - val_mse: 0.0212
Epoch 2/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 5.6207e-04 - mae: 0.0184 - mape: 17925.3984 - mse: 5.6207e-04 - val_loss: 0.0032 - val_mae: 0.0429 - val_mape: 3.9431 - val_mse: 0.0032
Epoch 3/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.5867e-04 - mae: 0.0141 - mape: 11721.6777 - mse: 3.5867e-04 - val_loss: 0.0016 - val_mae: 0.0304 - val_mape: 2.9129 - val_mse: 0.0016
Epoch 4/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.7198e-04 - mae: 0.0141 - mape: 8606.2471 - mse: 3.7198e-04 - val_loss: 0.0033 - val_mae: 0.0442 - val_mape: 3.9209 - val_mse: 0.0033
Epoch 5/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.6388e-04 - mae: 0.0142 - mape: 6735.6445 - mse: 3.6388e-04 - val_loss: 0.0042 - val_mae: 0.0492 - val_mape: 4.2665 - val_mse: 0.0042
Epoch 6/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.8548e-04 - mae: 0.0147 - mape: 5442.7739 - mse: 3.8548e-04 - val_loss: 0.0042 - val_mae: 0.0481 - val_mape: 4.1167 - val_mse: 0.0042
Epoch 7/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.6004e-04 - mae: 0.0143 - mape: 4939.2886 - mse: 3.6004e-04 - val_loss: 0.0034 - val_mae: 0.0425 - val_mape: 3.6522 - val_mse: 0.0034
Epoch 8/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.3646e-04 - mae: 0.0137 - mape: 5348.3037 - mse: 3.3646e-04 - val_loss: 0.0034 - val_mae: 0.0422 - val_mape: 3.6189 - val_mse: 0.0034
Epoch 9/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.5096e-04 - mae: 0.0140 - mape: 5265.4438 - mse: 3.5096e-04 - val_loss: 0.0035 - val_mae: 0.0429 - val_mape: 3.6664 - val_mse: 0.0035
Epoch 10/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.6610e-04 - mae: 0.0144 - mape: 5304.5278 - mse: 3.6610e-04 - val_loss: 0.0035 - val_mae: 0.0426 - val_mape: 3.6309 - val_mse: 0.0035
Epoch 11/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.3473e-04 - mae: 0.0135 - mape: 4721.1392 - mse: 3.3473e-04 - val_loss: 0.0041 - val_mae: 0.0472 - val_mape: 3.9940 - val_mse: 0.0041
Epoch 12/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.1016e-04 - mae: 0.0131 - mape: 4242.1709 - mse: 3.1016e-04 - val_loss: 0.0022 - val_mae: 0.0344 - val_mape: 3.1258 - val_mse: 0.0022
Epoch 13/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.2744e-04 - mae: 0.0136 - mape: 4704.4287 - mse: 3.2744e-04 - val_loss: 0.0029 - val_mae: 0.0384 - val_mape: 3.3422 - val_mse: 0.0029

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
model_2: Processando BBDC4 | Combinação 4...
Epoch 1/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 0.0546 - mae: 0.1575 - mape: 7237.3696 - mse: 0.0546 - val_loss: 0.0012 - val_mae: 0.0252 - val_mape: 4.8527 - val_mse: 0.0012
Epoch 2/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 7.0016e-04 - mae: 0.0196 - mape: 3745.9468 - mse: 7.0016e-04 - val_loss: 7.3870e-04 - val_mae: 0.0190 - val_mape: 3.7534 - val_mse: 7.3870e-04
Epoch 3/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.5457e-04 - mae: 0.0147 - mape: 1268.3656 - mse: 4.5457e-04 - val_loss: 6.5132e-04 - val_mae: 0.0180 - val_mape: 3.5620 - val_mse: 6.5132e-04
Epoch 4/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.4043e-04 - mae: 0.0144 - mape: 333.7034 - mse: 4.4043e-04 - val_loss: 6.8527e-04 - val_mae: 0.0191 - val_mape: 3.7318 - val_mse: 6.8527e-04
Epoch 5/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.4529e-04 - mae: 0.0144 - mape: 351.9709 - mse: 4.4529e-04 - val_loss: 7.1759e-04 - val_mae: 0.0199 - val_mape: 3.8539 - val_mse: 7.1759e-04
Epoch 6/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 5.7173e-04 - mae: 0.0163 - mape: 62.6266 - mse: 5.7173e-04 - val_loss: 7.4706e-04 - val_mae: 0.0205 - val_mape: 3.9409 - val_mse: 7.4706e-04
Epoch 7/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.8174e-04 - mae: 0.0151 - mape: 528.0704 - mse: 4.8174e-04 - val_loss: 6.7938e-04 - val_mae: 0.0193 - val_mape: 3.7351 - val_mse: 6.7938e-04
Epoch 8/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.6701e-04 - mae: 0.0147 - mape: 479.1728 - mse: 4.6701e-04 - val_loss: 5.7998e-04 - val_mae: 0.0170 - val_mape: 3.3847 - val_mse: 5.7998e-04
Epoch 9/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.6043e-04 - mae: 0.0148 - mape: 655.0811 - mse: 4.6043e-04 - val_loss: 6.0307e-04 - val_mae: 0.0175 - val_mape: 3.5056 - val_mse: 6.0307e-04
Epoch 10/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.5219e-04 - mae: 0.0144 - mape: 908.0801 - mse: 4.5219e-04 - val_loss: 6.0000e-04 - val_mae: 0.0175 - val_mape: 3.5117 - val_mse: 6.0000e-04
Epoch 11/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.4810e-04 - mae: 0.0144 - mape: 1136.4320 - mse: 4.4810e-04 - val_loss: 5.6404e-04 - val_mae: 0.0169 - val_mape: 3.3790 - val_mse: 5.6404e-04
Epoch 12/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.2887e-04 - mae: 0.0142 - mape: 1391.5988 - mse: 4.2887e-04 - val_loss: 5.4540e-04 - val_mae: 0.0167 - val_mape: 3.3164 - val_mse: 5.4540e-04
Epoch 13/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.4071e-04 - mae: 0.0145 - mape: 1475.0234 - mse: 4.4071e-04 - val_loss: 5.5938e-04 - val_mae: 0.0171 - val_mape: 3.3604 - val_mse: 5.5938e-04
Epoch 14/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.6346e-04 - mae: 0.0147 - mape: 1954.0718 - mse: 4.6346e-04 - val_loss: 5.4138e-04 - val_mae: 0.0167 - val_mape: 3.3161 - val_mse: 5.4138e-04
Epoch 15/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 4.6458e-04 - mae: 0.0148 - mape: 2345.5535 - mse: 4.6458e-04 - val_loss: 5.5691e-04 - val_mae: 0.0171 - val_mape: 3.3534 - val_mse: 5.5691e-04
Epoch 16/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 4.6534e-04 - mae: 0.0148 - mape: 1827.2719 - mse: 4.6534e-04 - val_loss: 5.3411e-04 - val_mae: 0.0166 - val_mape: 3.2828 - val_mse: 5.3411e-04
Epoch 17/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 5.0105e-04 - mae: 0.0153 - mape: 2294.3894 - mse: 5.0105e-04 - val_loss: 5.4264e-04 - val_mae: 0.0168 - val_mape: 3.3504 - val_mse: 5.4264e-04
Epoch 18/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.5569e-04 - mae: 0.0146 - mape: 2191.6821 - mse: 4.5569e-04 - val_loss: 5.4063e-04 - val_mae: 0.0168 - val_mape: 3.2956 - val_mse: 5.4063e-04
Epoch 19/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.6182e-04 - mae: 0.0147 - mape: 1758.2263 - mse: 4.6182e-04 - val_loss: 5.4627e-04 - val_mae: 0.0170 - val_mape: 3.3257 - val_mse: 5.4627e-04
Epoch 20/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.8511e-04 - mae: 0.0150 - mape: 1925.7889 - mse: 4.8511e-04 - val_loss: 5.2599e-04 - val_mae: 0.0165 - val_mape: 3.2688 - val_mse: 5.2599e-04
Epoch 21/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.6086e-04 - mae: 0.0147 - mape: 2046.8938 - mse: 4.6086e-04 - val_loss: 5.2553e-04 - val_mae: 0.0166 - val_mape: 3.2919 - val_mse: 5.2553e-04
Epoch 22/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 5.0176e-04 - mae: 0.0152 - mape: 1927.2098 - mse: 5.0176e-04 - val_loss: 5.8624e-04 - val_mae: 0.0178 - val_mape: 3.5547 - val_mse: 5.8624e-04
Epoch 23/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 4.7633e-04 - mae: 0.0150 - mape: 1708.0730 - mse: 4.7633e-04 - val_loss: 5.2964e-04 - val_mae: 0.0166 - val_mape: 3.2875 - val_mse: 5.2964e-04
Epoch 24/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.3953e-04 - mae: 0.0146 - mape: 1427.0132 - mse: 4.3953e-04 - val_loss: 5.9685e-04 - val_mae: 0.0181 - val_mape: 3.6128 - val_mse: 5.9685e-04
Epoch 25/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.3547e-04 - mae: 0.0142 - mape: 1585.5768 - mse: 4.3547e-04 - val_loss: 5.3599e-04 - val_mae: 0.0168 - val_mape: 3.3457 - val_mse: 5.3599e-04
Epoch 26/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.5570e-04 - mae: 0.0148 - mape: 1656.0479 - mse: 4.5570e-04 - val_loss: 5.2400e-04 - val_mae: 0.0165 - val_mape: 3.2831 - val_mse: 5.2400e-04
Epoch 27/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 4.7987e-04 - mae: 0.0151 - mape: 1002.6465 - mse: 4.7987e-04 - val_loss: 5.5724e-04 - val_mae: 0.0173 - val_mape: 3.4508 - val_mse: 5.5724e-04
Epoch 28/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.0245e-04 - mae: 0.0139 - mape: 1767.7832 - mse: 4.0245e-04 - val_loss: 5.3166e-04 - val_mae: 0.0168 - val_mape: 3.3375 - val_mse: 5.3166e-04
Epoch 29/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.7741e-04 - mae: 0.0151 - mape: 1088.7068 - mse: 4.7741e-04 - val_loss: 5.1961e-04 - val_mae: 0.0164 - val_mape: 3.2452 - val_mse: 5.1961e-04
Epoch 30/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.0097e-04 - mae: 0.0137 - mape: 1107.2700 - mse: 4.0097e-04 - val_loss: 6.6265e-04 - val_mae: 0.0194 - val_mape: 3.8815 - val_mse: 6.6265e-04
Epoch 31/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.4628e-04 - mae: 0.0146 - mape: 2181.7869 - mse: 4.4628e-04 - val_loss: 5.4157e-04 - val_mae: 0.0170 - val_mape: 3.3791 - val_mse: 5.4157e-04
Epoch 32/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.3775e-04 - mae: 0.0142 - mape: 834.5661 - mse: 4.3775e-04 - val_loss: 5.3667e-04 - val_mae: 0.0168 - val_mape: 3.3538 - val_mse: 5.3667e-04
Epoch 33/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 4.5945e-04 - mae: 0.0147 - mape: 1287.7428 - mse: 4.5945e-04 - val_loss: 5.6408e-04 - val_mae: 0.0174 - val_mape: 3.4783 - val_mse: 5.6408e-04
Epoch 34/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.2541e-04 - mae: 0.0146 - mape: 1380.4611 - mse: 4.2541e-04 - val_loss: 5.6034e-04 - val_mae: 0.0174 - val_mape: 3.4657 - val_mse: 5.6034e-04
Epoch 35/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.2120e-04 - mae: 0.0143 - mape: 980.8620 - mse: 4.2120e-04 - val_loss: 5.1751e-04 - val_mae: 0.0164 - val_mape: 3.2466 - val_mse: 5.1751e-04
Epoch 36/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.1811e-04 - mae: 0.0142 - mape: 1878.7690 - mse: 4.1811e-04 - val_loss: 5.1726e-04 - val_mae: 0.0164 - val_mape: 3.2470 - val_mse: 5.1726e-04
Epoch 37/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.3302e-04 - mae: 0.0144 - mape: 1605.0625 - mse: 4.3302e-04 - val_loss: 5.1852e-04 - val_mae: 0.0164 - val_mape: 3.2361 - val_mse: 5.1852e-04
Epoch 38/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.9806e-04 - mae: 0.0136 - mape: 1388.2328 - mse: 3.9806e-04 - val_loss: 5.3756e-04 - val_mae: 0.0169 - val_mape: 3.2874 - val_mse: 5.3756e-04
Epoch 39/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.0412e-04 - mae: 0.0139 - mape: 1717.5394 - mse: 4.0412e-04 - val_loss: 5.4705e-04 - val_mae: 0.0170 - val_mape: 3.3114 - val_mse: 5.4705e-04
Epoch 40/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.4555e-04 - mae: 0.0146 - mape: 720.4358 - mse: 4.4555e-04 - val_loss: 6.2255e-04 - val_mae: 0.0187 - val_mape: 3.5819 - val_mse: 6.2255e-04
Epoch 41/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.4371e-04 - mae: 0.0145 - mape: 1422.3134 - mse: 4.4371e-04 - val_loss: 5.3527e-04 - val_mae: 0.0168 - val_mape: 3.2868 - val_mse: 5.3527e-04
Epoch 42/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.2441e-04 - mae: 0.0142 - mape: 1500.3274 - mse: 4.2441e-04 - val_loss: 7.6991e-04 - val_mae: 0.0216 - val_mape: 4.0802 - val_mse: 7.6991e-04
Epoch 43/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.6957e-04 - mae: 0.0147 - mape: 749.3904 - mse: 4.6957e-04 - val_loss: 9.7825e-04 - val_mae: 0.0254 - val_mape: 4.7551 - val_mse: 9.7825e-04
Epoch 44/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.6027e-04 - mae: 0.0148 - mape: 813.6785 - mse: 4.6027e-04 - val_loss: 6.5195e-04 - val_mae: 0.0193 - val_mape: 3.7195 - val_mse: 6.5195e-04
Epoch 45/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.6477e-04 - mae: 0.0148 - mape: 791.0956 - mse: 4.6477e-04 - val_loss: 7.6214e-04 - val_mae: 0.0215 - val_mape: 4.0880 - val_mse: 7.6214e-04
Epoch 46/50
88/88 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.1069e-04 - mae: 0.0139 - mape: 2355.6702 - mse: 4.1069e-04 - val_loss: 8.4516e-04 - val_mae: 0.0230 - val_mape: 4.3308 - val_mse: 8.4516e-04

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
model_2: Processando ITUB4 | Combinação 4...
Epoch 1/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 6s 24ms/step - loss: 0.0589 - mae: 0.1671 - mape: 116954.7422 - mse: 0.0589 - val_loss: 9.6152e-04 - val_mae: 0.0231 - val_mape: 3.8310 - val_mse: 9.6152e-04
Epoch 2/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 4.2049e-04 - mae: 0.0153 - mape: 52900.8633 - mse: 4.2049e-04 - val_loss: 6.0680e-04 - val_mae: 0.0175 - val_mape: 2.9280 - val_mse: 6.0680e-04
Epoch 3/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.8819e-04 - mae: 0.0126 - mape: 39301.0195 - mse: 2.8819e-04 - val_loss: 5.3639e-04 - val_mae: 0.0164 - val_mape: 2.7703 - val_mse: 5.3639e-04
Epoch 4/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.6563e-04 - mae: 0.0119 - mape: 32525.7852 - mse: 2.6563e-04 - val_loss: 6.9328e-04 - val_mae: 0.0194 - val_mape: 3.3007 - val_mse: 6.9328e-04
Epoch 5/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.8124e-04 - mae: 0.0124 - mape: 29651.9805 - mse: 2.8124e-04 - val_loss: 5.2308e-04 - val_mae: 0.0160 - val_mape: 2.7388 - val_mse: 5.2308e-04
Epoch 6/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.5420e-04 - mae: 0.0117 - mape: 30498.5000 - mse: 2.5420e-04 - val_loss: 5.1096e-04 - val_mae: 0.0159 - val_mape: 2.7055 - val_mse: 5.1096e-04
Epoch 7/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.1049e-04 - mae: 0.0129 - mape: 29132.5625 - mse: 3.1049e-04 - val_loss: 7.2692e-04 - val_mae: 0.0202 - val_mape: 3.4235 - val_mse: 7.2692e-04
Epoch 8/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.4779e-04 - mae: 0.0156 - mape: 28421.7148 - mse: 4.4779e-04 - val_loss: 4.8803e-04 - val_mae: 0.0156 - val_mape: 2.6451 - val_mse: 4.8803e-04
Epoch 9/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 4.3794e-04 - mae: 0.0152 - mape: 27831.8105 - mse: 4.3794e-04 - val_loss: 4.7871e-04 - val_mae: 0.0155 - val_mape: 2.6286 - val_mse: 4.7871e-04
Epoch 10/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.0152e-04 - mae: 0.0126 - mape: 26908.0762 - mse: 3.0152e-04 - val_loss: 6.6485e-04 - val_mae: 0.0192 - val_mape: 3.2533 - val_mse: 6.6485e-04
Epoch 11/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 4.5308e-04 - mae: 0.0156 - mape: 28164.8145 - mse: 4.5308e-04 - val_loss: 6.4925e-04 - val_mae: 0.0189 - val_mape: 3.2311 - val_mse: 6.4925e-04
Epoch 12/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.6314e-04 - mae: 0.0140 - mape: 26919.8711 - mse: 3.6314e-04 - val_loss: 4.5614e-04 - val_mae: 0.0152 - val_mape: 2.5786 - val_mse: 4.5614e-04
Epoch 13/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 3.3212e-04 - mae: 0.0134 - mape: 23980.4785 - mse: 3.3212e-04 - val_loss: 4.5150e-04 - val_mae: 0.0152 - val_mape: 2.5669 - val_mse: 4.5150e-04
Epoch 14/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.6503e-04 - mae: 0.0138 - mape: 26646.1172 - mse: 3.6503e-04 - val_loss: 4.8158e-04 - val_mae: 0.0161 - val_mape: 2.6841 - val_mse: 4.8158e-04
Epoch 15/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.4670e-04 - mae: 0.0135 - mape: 24341.5215 - mse: 3.4670e-04 - val_loss: 4.8394e-04 - val_mae: 0.0158 - val_mape: 2.6808 - val_mse: 4.8394e-04
Epoch 16/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 4.1818e-04 - mae: 0.0149 - mape: 25583.8457 - mse: 4.1818e-04 - val_loss: 4.6164e-04 - val_mae: 0.0153 - val_mape: 2.6045 - val_mse: 4.6164e-04
Epoch 17/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.5863e-04 - mae: 0.0139 - mape: 23766.6074 - mse: 3.5863e-04 - val_loss: 4.7727e-04 - val_mae: 0.0157 - val_mape: 2.6748 - val_mse: 4.7727e-04
Epoch 18/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.5646e-04 - mae: 0.0138 - mape: 25128.5176 - mse: 3.5646e-04 - val_loss: 5.1934e-04 - val_mae: 0.0166 - val_mape: 2.8303 - val_mse: 5.1934e-04
Epoch 19/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.1096e-04 - mae: 0.0129 - mape: 23811.1777 - mse: 3.1096e-04 - val_loss: 4.4684e-04 - val_mae: 0.0151 - val_mape: 2.5725 - val_mse: 4.4684e-04
Epoch 20/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.5513e-04 - mae: 0.0138 - mape: 23155.1641 - mse: 3.5513e-04 - val_loss: 4.5708e-04 - val_mae: 0.0154 - val_mape: 2.6094 - val_mse: 4.5708e-04
Epoch 21/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.8582e-04 - mae: 0.0144 - mape: 24210.9375 - mse: 3.8582e-04 - val_loss: 7.0908e-04 - val_mae: 0.0206 - val_mape: 3.4790 - val_mse: 7.0908e-04
Epoch 22/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.6060e-04 - mae: 0.0141 - mape: 22950.2148 - mse: 3.6060e-04 - val_loss: 4.2252e-04 - val_mae: 0.0149 - val_mape: 2.5094 - val_mse: 4.2252e-04
Epoch 23/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.8001e-04 - mae: 0.0122 - mape: 24046.9062 - mse: 2.8001e-04 - val_loss: 4.4244e-04 - val_mae: 0.0151 - val_mape: 2.5702 - val_mse: 4.4244e-04
Epoch 24/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 5.5474e-04 - mae: 0.0172 - mape: 25028.1152 - mse: 5.5474e-04 - val_loss: 4.8679e-04 - val_mae: 0.0162 - val_mape: 2.7460 - val_mse: 4.8679e-04
Epoch 25/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.6533e-04 - mae: 0.0140 - mape: 24037.9277 - mse: 3.6533e-04 - val_loss: 4.2121e-04 - val_mae: 0.0147 - val_mape: 2.5002 - val_mse: 4.2121e-04
Epoch 26/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 2.5442e-04 - mae: 0.0116 - mape: 23816.3281 - mse: 2.5442e-04 - val_loss: 4.6057e-04 - val_mae: 0.0156 - val_mape: 2.6499 - val_mse: 4.6057e-04
Epoch 27/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 4.2716e-04 - mae: 0.0154 - mape: 22847.2910 - mse: 4.2716e-04 - val_loss: 4.3750e-04 - val_mae: 0.0151 - val_mape: 2.5709 - val_mse: 4.3750e-04
Epoch 28/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.0622e-04 - mae: 0.0128 - mape: 21564.7676 - mse: 3.0622e-04 - val_loss: 6.3245e-04 - val_mae: 0.0191 - val_mape: 3.2377 - val_mse: 6.3245e-04
Epoch 29/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 3.1888e-04 - mae: 0.0132 - mape: 23894.6914 - mse: 3.1888e-04 - val_loss: 4.1207e-04 - val_mae: 0.0146 - val_mape: 2.4757 - val_mse: 4.1207e-04
Epoch 30/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 2.9077e-04 - mae: 0.0124 - mape: 23380.1328 - mse: 2.9077e-04 - val_loss: 4.1959e-04 - val_mae: 0.0148 - val_mape: 2.5068 - val_mse: 4.1959e-04
Epoch 31/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.2111e-04 - mae: 0.0132 - mape: 22620.7441 - mse: 3.2111e-04 - val_loss: 4.7140e-04 - val_mae: 0.0159 - val_mape: 2.7174 - val_mse: 4.7140e-04
Epoch 32/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.4914e-04 - mae: 0.0139 - mape: 23316.4668 - mse: 3.4914e-04 - val_loss: 5.0374e-04 - val_mae: 0.0166 - val_mape: 2.8148 - val_mse: 5.0374e-04
Epoch 33/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.2901e-04 - mae: 0.0133 - mape: 22205.2305 - mse: 3.2901e-04 - val_loss: 4.4702e-04 - val_mae: 0.0154 - val_mape: 2.6206 - val_mse: 4.4702e-04
Epoch 34/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 2.7478e-04 - mae: 0.0122 - mape: 23619.5957 - mse: 2.7478e-04 - val_loss: 4.7594e-04 - val_mae: 0.0161 - val_mape: 2.7331 - val_mse: 4.7594e-04
Epoch 35/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.4483e-04 - mae: 0.0137 - mape: 22599.5723 - mse: 3.4483e-04 - val_loss: 3.9918e-04 - val_mae: 0.0145 - val_mape: 2.4437 - val_mse: 3.9918e-04
Epoch 36/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.6927e-04 - mae: 0.0120 - mape: 21854.4453 - mse: 2.6927e-04 - val_loss: 4.7243e-04 - val_mae: 0.0161 - val_mape: 2.7236 - val_mse: 4.7243e-04
Epoch 37/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.5285e-04 - mae: 0.0137 - mape: 20600.6504 - mse: 3.5285e-04 - val_loss: 4.3510e-04 - val_mae: 0.0152 - val_mape: 2.5859 - val_mse: 4.3510e-04
Epoch 38/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 2.8793e-04 - mae: 0.0124 - mape: 19631.1875 - mse: 2.8793e-04 - val_loss: 3.9760e-04 - val_mae: 0.0145 - val_mape: 2.4377 - val_mse: 3.9760e-04
Epoch 39/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.3459e-04 - mae: 0.0133 - mape: 20124.4453 - mse: 3.3459e-04 - val_loss: 4.2519e-04 - val_mae: 0.0150 - val_mape: 2.5484 - val_mse: 4.2519e-04
Epoch 40/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 2.8480e-04 - mae: 0.0123 - mape: 21330.2461 - mse: 2.8480e-04 - val_loss: 3.9693e-04 - val_mae: 0.0145 - val_mape: 2.4367 - val_mse: 3.9693e-04
Epoch 41/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 3.2684e-04 - mae: 0.0132 - mape: 19524.4629 - mse: 3.2684e-04 - val_loss: 4.0248e-04 - val_mae: 0.0146 - val_mape: 2.4541 - val_mse: 4.0248e-04
Epoch 42/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.6386e-04 - mae: 0.0119 - mape: 20856.9688 - mse: 2.6386e-04 - val_loss: 3.9564e-04 - val_mae: 0.0145 - val_mape: 2.4293 - val_mse: 3.9564e-04
Epoch 43/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 3.1341e-04 - mae: 0.0129 - mape: 20290.0605 - mse: 3.1341e-04 - val_loss: 4.1057e-04 - val_mae: 0.0148 - val_mape: 2.5064 - val_mse: 4.1057e-04
Epoch 44/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.1806e-04 - mae: 0.0131 - mape: 23292.9805 - mse: 3.1806e-04 - val_loss: 3.9826e-04 - val_mae: 0.0145 - val_mape: 2.4549 - val_mse: 3.9826e-04
Epoch 45/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.1296e-04 - mae: 0.0129 - mape: 18686.3301 - mse: 3.1296e-04 - val_loss: 4.5829e-04 - val_mae: 0.0158 - val_mape: 2.6820 - val_mse: 4.5829e-04
Epoch 46/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.1959e-04 - mae: 0.0130 - mape: 20889.5840 - mse: 3.1959e-04 - val_loss: 3.9829e-04 - val_mae: 0.0145 - val_mape: 2.4552 - val_mse: 3.9829e-04
Epoch 47/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.8389e-04 - mae: 0.0123 - mape: 21193.0391 - mse: 2.8389e-04 - val_loss: 3.9195e-04 - val_mae: 0.0144 - val_mape: 2.4321 - val_mse: 3.9195e-04
Epoch 48/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.2193e-04 - mae: 0.0132 - mape: 19203.1523 - mse: 3.2193e-04 - val_loss: 3.9228e-04 - val_mae: 0.0144 - val_mape: 2.4361 - val_mse: 3.9228e-04
Epoch 49/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 3.0114e-04 - mae: 0.0127 - mape: 18883.6367 - mse: 3.0114e-04 - val_loss: 4.2938e-04 - val_mae: 0.0153 - val_mape: 2.5473 - val_mse: 4.2938e-04
Epoch 50/50
90/90 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 2.7229e-04 - mae: 0.0119 - mape: 20376.2305 - mse: 2.7229e-04 - val_loss: 4.1021e-04 - val_mae: 0.0148 - val_mape: 2.4736 - val_mse: 4.1021e-04

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step

## 3. Processar o Backtest com Modelo salvo

In [ ]:
# Execute apenas se pulou a etapa anterior e deseja carregar os artefatos

name_model = 'model_2' # Modelo 2
num_combination = 5 # Combinação 5

In [5]:
results, signals = process_stocks(stock_list, all_stock_data, name_model, num_combination)

Processando PETR4...

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
PETR4 processado!
Processando VALE3...

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step
VALE3 processado!
Processando BBDC4...

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
BBDC4 processado!
Processando ITUB4...

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step
ITUB4 processado!

In [6]:
plot_all_results(results, signals, name_model, num_combination)

In [10]:
# Combinação 5: Google News + Twitter + IFR + MMS
final_results_df = calculate_final_results(results, signals)
final_results_df

,Ativo,Estratégia (Modelo 2) (R$),Buy & Hold (R$),Retorno Estratégia (%),Retorno Buy & Hold (%)
0,PETR4,R$ 13426.86,R$ 10739.39,34.27%,7.39%
1,VALE3,R$ 13114.02,R$ 15489.48,31.14%,54.89%
2,BBDC4,R$ 14383.19,R$ 6553.20,43.83%,-34.47%
3,ITUB4,R$ 12249.94,R$ 6668.49,22.50%,-33.32%

In [7]:
# Combinação 4. Stock Data + (IFR + MMS + MME) 
final_results_df = calculate_final_results(results, signals)
final_results_df

,Ativo,Estratégia (Modelo 2) (R$),Buy & Hold (R$),Retorno Estratégia (%),Retorno Buy & Hold (%)
0,PETR4,R$ 17504.55,R$ 10739.39,75.05%,7.39%
1,VALE3,R$ 15442.85,R$ 15489.48,54.43%,54.89%
2,BBDC4,R$ 12441.31,R$ 6553.20,24.41%,-34.47%
3,ITUB4,R$ 7050.50,R$ 6668.49,-29.50%,-33.32%